name: allinfra-iac

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string
      action:
        required: true
        type: string
      region:
        required: true
        type: string
      subscription_id:
        required: true
        type: string
      terraform_version:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
  workflow_dispatch:
    inputs:
      branch:
        description: Git branch to execute
        required: true
        default: main
      environment:
        description: Deployment environment
        required: true
        type: choice
        options: [dev, prod]
      action:
        description: Terraform operation
        required: true
        type: choice
        options: [validate, plan, apply]
      region:
        description: Azure region
        required: true
        default: eastus
      subscription_id:
        description: Azure Subscription ID
        required: true
      terraform_version:
        description: Terraform CLI version
        required: true
        default: 1.9.8

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  validate:
    if: ${{ inputs.action == 'validate' }}
    uses: ./.github/workflows/terraform-ci.yml
    with:
      branch: ${{ inputs.branch }}
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      subscription_id: ${{ inputs.subscription_id }}
      terraform_version: ${{ inputs.terraform_version }}
    secrets: inherit

  plan:
    if: ${{ inputs.action == 'plan' }}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      branch: ${{ inputs.branch }}
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      subscription_id: ${{ inputs.subscription_id }}
      terraform_version: ${{ inputs.terraform_version }}
    secrets: inherit

  apply:
    if: ${{ inputs.action == 'apply' }}
    uses: ./.github/workflows/terraform-apply.yml
    with:
      branch: ${{ inputs.branch }}
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      subscription_id: ${{ inputs.subscription_id }}
      terraform_version: ${{ inputs.terraform_version }}
    secrets: inherit
